export const allQuestions: string[] = [
  "What is something you're proud of today?",
  "Who did you connect with today?",
  "What are you grateful for right now?",
  "Did anything surprise you today?",
  "What did you learn?",
  "What's the best thing you've eaten this week?",
  "Describe your mood in one word.",
  "What's one goal you have for this week?",
  "How did you relax or unwind today?",
  "What made you smile today?",
  "What's something you're looking forward to?",
  "What's something you're struggling with?",
  "What's something you're curious about?",
  "What's something you're excited about?",
  "What's your favorite family meal we've had together?",
  "If you could recommend one movie, what would it be and why?",
  "How was the weather today where you are?",
  "What's your favorite dish to cook, and would you like to teach us how?",
  "What's a memorable meal we've shared that stands out to you?",
  "What's your favorite snack, and when do you usually enjoy it?",
  "How do you like your coffee or tea in the morning?",
  "What's your favorite restaurant that we've been to as a family?",
  "What's your favorite comfort food and why?",
  "Do you have a favorite food memory from your childhood?",
  "What's a food you've always wanted to try but haven't yet?",
  "If you could create a signature family dish, what would it include?",
  "What's your favorite fruit or vegetable, and how do you like it prepared?",
  "How do you feel about spicy food?",
  "What's your favorite dessert that we make at home?",
  "Do you prefer cooking at home or dining out, and why?",
  "What's your go-to meal when you're short on time?",
  "How do you like to start your day breakfast-wise?",
  "What's your favorite beverage to have with meals?",
  "Do you have any dietary preferences or restrictions you'd like to share?",
  "What's a meal that brings back fond memories for you?",
  "How do you like to celebrate special occasions with food?",
  "What's your favorite way to unwind after a long day?",
  "If you could learn any new skill, what would it be and why?",
  "What's a hobby you've always wanted to try but haven't yet?",
  "What's your favorite way to spend a weekend?",
  "How do you like to stay active and healthy?",
  "What's a book that has had a significant impact on you?",
  "If you could travel anywhere in the world, where would you go and why?",
  "What's your favorite family tradition?",
  "How do you prefer to communicate when we're apart?",
  "What's something new you'd like to introduce to our family routine?",
  "How do you handle stress, and is there something we can do to support you?",
  "What's a personal achievement you're working towards?",
  "How do you like to celebrate your achievements?",
  "What's a favorite memory from our family vacations?",
  "If you could relive any day from the past year, which would it be and why?",
  "What's something you've always wanted to learn more about?",
  "What's your favorite way to express creativity?",
  "If you could change one thing about your daily routine, what would it be?",
  "What's something that always makes you laugh?",
  "How do you stay motivated during challenging times?",
  "What's a goal you have for our family this year?",
  "How do you like to give and receive support from family members?",
  "What's something you'd like to share about your day that we might not know?",
  "How do you feel about technology and its role in our lives?",
  "What's your favorite way to relax on a day off?",
  "If you could have any superpower, what would it be and why?",
  "What's a skill you'd like to develop in the next few years?",
  "How do you prioritize your personal well-being?",
  "What's something you're passionate about and why?",
  "How do you celebrate personal milestones?",

  // **Childhood & Memories**
  "What is your favorite childhood memory?",
  "Who was your best friend growing up, and what did you enjoy doing together?",
  "What was your favorite game or toy as a child?",
  "Did you have any pets when you were growing up? Tell us about them.",
  "What was your favorite subject in school and why?",
  "Can you share a funny story from your school days?",
  "What traditions did your family have when you were a child?",

  // **Dreams & Aspirations**
  "What was your dream job when you were younger?",
  "Is there something you've always wanted to achieve but haven't yet?",
  "Where do you see yourself in five years?",
  "If you could live in any era, which would you choose and why?",
  "What personal goals are you currently working towards?",
  "What is one thing you'd like to accomplish in your lifetime?",

  // **Values & Beliefs**
  "What values are most important to you?",
  "How do you define success?",
  "What principles guide your decisions in life?",
  "Is there a belief or philosophy that you strongly adhere to?",
  "How do you practice gratitude in your daily life?",
  "What does integrity mean to you?",

  // **Hobbies & Interests**
  "What hobbies do you enjoy in your free time?",
  "Is there a hobby you'd like to take up in the future?",
  "What's your favorite way to spend a rainy day?",
  "Do you have a favorite sport or physical activity?",
  "What's a creative project you've worked on recently?",
  "What type of music do you enjoy listening to the most?",

  // **Personal Preferences**
  "What's your favorite book so far and why?",
  "Do you have a favorite quote or saying that inspires you?",
  "What's your favorite way to spend a holiday?",
  "Do you prefer mornings or evenings? Why?",
  "What's your favorite season and what do you love about it?",
  "Do you have a favorite place in our home? Why is it special to you?",

  // **Relationships & Connections**
  "How did you meet your closest friends?",
  "What's the most valuable lesson you've learned from a relationship?",
  "How do you maintain strong relationships with loved ones?",
  "What's something you appreciate about each family member?",
  "How do you show love and appreciation to others?",

  // **Life Experiences**
  "What's the most adventurous thing you've ever done?",
  "Have you ever faced a significant challenge? How did you overcome it?",
  "What's a memorable trip you've taken and why?",
  "Can you share a pivotal moment in your life?",

  // **Favorites & Preferences**
  "What's your favorite movie genre and why?",
  "Do you have a favorite artist or painter?",
  "What's your favorite way to celebrate your birthday?",
  "What's your favorite holiday and how do you like to celebrate it?",
  "Do you have a favorite board game or card game?",
  "What's your favorite way to spend time outdoors?",

  // **Future & Imagination**
  "If you could time travel, where would you go and why?",
  "What invention do you wish existed?",
  "If you could meet any historical figure, who would it be and why?",
  "What does your ideal day look like?",
  "If you could redesign our family home, what changes would you make?",

  // **Personal Growth**
  "What habit are you trying to build or break?",
  "How do you handle setbacks or failures?",
  "What's something new you've learned about yourself recently?",
  "How do you stay inspired and motivated?",
  "What do you do to maintain a healthy work-life balance?",

  // **Miscellaneous**
  "If you could describe yourself using three words, what would they be?",
  "What's something you've always wanted to ask me but haven't yet?",
  "How do you like to celebrate achievements, both big and small?",
  "What's a tradition you'd like to start with our family?",
  "Do you have a favorite quote or motto that you live by?",
  "What's one thing you'd like to improve about our family dynamic?",
];
