// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcP4UYdPbo853JLGomD3TPEzBqqrvVJA8',
    appId: '1:448976016086:web:e0f0c0db3a48f3de17af77',
    messagingSenderId: '448976016086',
    projectId: 'dearfamz',
    authDomain: 'dearfamz.firebaseapp.com',
    storageBucket: 'dearfamz.firebasestorage.app',
    measurementId: 'G-965YFFN5WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVSShU0vbudrYalQq0VejRMd4ukadVx98',
    appId: '1:448976016086:android:a4c5b2419dcf055f17af77',
    messagingSenderId: '448976016086',
    projectId: 'dearfamz',
    storageBucket: 'dearfamz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrH8tO9vQK00e_nFJNELYQYn5U3zZ39I',
    appId: '1:448976016086:ios:fb2e6998882e387217af77',
    messagingSenderId: '448976016086',
    projectId: 'dearfamz',
    storageBucket: 'dearfamz.firebasestorage.app',
    iosBundleId: 'com.example.dearfamz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrH8tO9vQK00e_nFJNELYQYn5U3zZ39I',
    appId: '1:448976016086:ios:fb2e6998882e387217af77',
    messagingSenderId: '448976016086',
    projectId: 'dearfamz',
    storageBucket: 'dearfamz.firebasestorage.app',
    iosBundleId: 'com.example.dearfamz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcP4UYdPbo853JLGomD3TPEzBqqrvVJA8',
    appId: '1:448976016086:web:bb60a4a3486ff1e617af77',
    messagingSenderId: '448976016086',
    projectId: 'dearfamz',
    authDomain: 'dearfamz.firebaseapp.com',
    storageBucket: 'dearfamz.firebasestorage.app',
    measurementId: 'G-EK48CXV13E',
  );
}
